-file("/usr/local/lib/erlang/lib/parsetools-2.1.1/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(cf_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/cf_lexer.xrl", 114).

-author( "Jorgen Brandt <brandjoe@hu-berlin.de>" ).

-export( [yyrev/2] ).

-ifdef( TEST ).
-include_lib( "eunit/include/eunit.hrl" ).
-endif.

trim_body( S ) ->
  string:substr( S, 3, length( S )-4 ).
  
trim_strlit( S ) ->
  string:substr( S, 2, length( S )-2 ).
  


%% =============================================================================
%% Unit Tests
%% =============================================================================

  
-ifdef( TEST ).



bash_style_comment_should_be_recognized_test() ->
  ?assertEqual( {ok, [], 1}, string( "#this is a comment" ) ).
  
c_style_comment_should_be_recognized_test() ->
  ?assertEqual( {ok, [], 1}, string( "//this is a comment" ) ).
  
erlang_style_comment_should_be_recognized_test() ->
  ?assertEqual( {ok, [], 1}, string( "%this is a comment" ) ).
  
  
multiline_comment_should_be_recognized_test() ->
  [?assertEqual( {ok, [], 1}, string( "/**/" ) ),
   ?assertEqual( {ok, [], 1}, string( "/*x*/" ) ),
   ?assertEqual( {ok, [], 1}, string( "/*xy*/" ) ),
   ?assertEqual( {ok, [], 2}, string( "/*x\ny*/" ) )].
    
bash_should_be_recognized_test() ->
  ?assertEqual( {ok, [{bash, 1, "bash"}], 1}, string( "bash" ) ).
  
beginif_should_be_recognized_test() ->
  ?assertEqual( {ok, [{beginif, 1, "if"}], 1}, string( "if" ) ).
  
colon_should_be_recognized_test() ->
  ?assertEqual( {ok, [{colon, 1, ":"}], 1}, string( ":" ) ).
  
deftask_should_be_recognized_test() ->
  ?assertEqual( {ok, [{deftask, 1, "deftask"}], 1}, string( "deftask" ) ).

else_should_be_recognized_test() ->
  ?assertEqual( {ok, [{else, 1, "else"}], 1}, string( "else" ) ).

endif_should_be_recognized_test() ->
  ?assertEqual( {ok, [{endif, 1, "end"}], 1}, string( "end" ) ).

eq_should_be_recognized_test() ->
  ?assertEqual( {ok, [{eq, 1, "="}], 1}, string( "=" ) ).

file_should_be_recognized_test() ->
  ?assertEqual( {ok, [{file, 1, "File"}], 1}, string( "File" ) ).

in_should_be_recognized_test() ->
  ?assertEqual( {ok, [{in, 1, "in"}], 1}, string( "in" ) ).
  
id_should_be_recognized_test() ->
  [?assertEqual( {ok, [{id, 1, "inp"}], 1}, string( "inp" ) ),
   ?assertEqual( {ok, [{id, 1, "a0"}], 1}, string( "a0" ) ),
   ?assertEqual( {ok, [{id, 1, "a9"}], 1}, string( "a9" ) ),
   ?assertEqual( {ok, [{id, 1, "a."}], 1}, string( "a." ) ),
   ?assertEqual( {ok, [{id, 1, "a-"}], 1}, string( "a-" ) ),
   ?assertEqual( {ok, [{id, 1, "a_"}], 1}, string( "a_" ) )].
    
python_should_be_recognized_test() ->
  ?assertEqual( {ok, [{python, 1, "python"}], 1}, string( "python" ) ).
  
r_should_be_recognized_test() ->
  [?assertEqual( {ok, [{r, 1, "r"}], 1}, string( "r" ) ),
   ?assertEqual( {ok, [{r, 1, "R"}], 1}, string( "R" ) )].

lbrace_should_be_recognized_test() ->
  ?assertEqual( {ok, [{lbrace, 1, "{"}], 1}, string( "{" ) ).
  
lparen_should_be_recognized_test() ->
  ?assertEqual( {ok, [{lparen, 1, "("}], 1}, string( "(" ) ).
  
lsquarebr_should_be_recognized_test() ->
  ?assertEqual( {ok, [{lsquarebr, 1, "["}], 1}, string( "[" ) ).
  
ltag_should_be_recognized_test() ->
  ?assertEqual( {ok, [{ltag, 1, "<"}], 1}, string( "<" ) ).
  
nil_should_be_recognized_test() ->
  ?assertEqual( {ok, [{nil, 1, "nil"}], 1}, string( "nil" ) ).
    
rbrace_should_be_recognized_test() ->
  ?assertEqual( {ok, [{rbrace, 1, "}"}], 1}, string( "}" ) ).
  
rparen_should_be_recognized_test() ->
  ?assertEqual( {ok, [{rparen, 1, ")"}], 1}, string( ")" ) ).
  
rsquarebr_should_be_recognized_test() ->
  ?assertEqual( {ok, [{rsquarebr, 1, "]"}], 1}, string( "]" ) ).
  
rtag_should_be_recognized_test() ->
  ?assertEqual( {ok, [{rtag, 1, ">"}], 1}, string( ">" ) ).
  
semicolon_should_be_recognized_test() ->
  ?assertEqual( {ok, [{semicolon, 1, ";"}], 1}, string( ";" ) ).
  
string_should_be_recognized_test() ->
  ?assertEqual( {ok, [{string, 1, "String"}], 1}, string( "String" ) ).
  
then_should_be_recognized_test() ->
  ?assertEqual( {ok, [{then, 1, "then"}], 1}, string( "then" ) ).
  
intlit_should_be_recognized_test() ->
  [?assertEqual( {ok, [{intlit, 1, "10"}], 1}, string( "10" ) ),
   ?assertEqual( {ok, [{intlit, 1, "-10"}], 1}, string( "-10" ) ),
   ?assertEqual( {ok, [{intlit, 1, "9"}], 1}, string( "9" ) ),
   ?assertEqual( {ok, [{intlit, 1, "0"}], 1}, string( "0" ) )].
   
body_should_be_recognized_test() ->
  [?assertEqual( {ok, [{body, 1, ""}], 1}, string( "*{}*" ) ),
   ?assertEqual( {ok, [{body, 1, "x"}], 1}, string( "*{x}*" ) ),
   ?assertEqual( {ok, [{body, 1, "xy"}], 1}, string( "*{xy}*" ) ),
   ?assertEqual( {ok, [{body, 1, "x\ny"}], 2}, string( "*{x\ny}*" ) )].
   
strlit_should_be_recognized_test() ->
  [?assertEqual( {ok, [{strlit, 1, ""}], 1}, string( "\"\"" ) ),
   ?assertEqual( {ok, [{strlit, 1, "x"}], 1}, string( "\"x\"" ) ),
   ?assertEqual( {ok, [{strlit, 1, "xy"}], 1}, string( "\"xy\"" ) )].

   
   
   

-endif.
  


-file("/usr/local/lib/erlang/lib/parsetools-2.1.1/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/cf_lexer.erl", 428).
yystate() -> 69.

yystate(72, [122|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [121|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 120 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,72};
yystate(71, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 2, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,70};
yystate(69, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [81|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line+1, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 67, C =< 69 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 79 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 84, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 102, C =< 104 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 109 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(69, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,69};
yystate(68, [116|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,68};
yystate(67, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line+1, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 25, Tlen);
yystate(66, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 25, Tlen);
yystate(66, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 25, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 25, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 25, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 25, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,66};
yystate(65, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(64, [104|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,64};
yystate(63, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(62, [103|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 27, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(62, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(62, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,62};
yystate(61, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(60, [111|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,60};
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(59, Ics, Line, Tlen+1, 28, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(59, Ics, Line, Tlen+1, 28, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,59};
yystate(58, [110|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 27, Tlen);
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(58, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(58, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,58};
yystate(57, [104|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,57};
yystate(56, [110|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,56};
yystate(55, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(54, [105|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 27, Tlen);
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(54, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(54, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,54};
yystate(53, [101|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 27, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(53, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(53, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,53};
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 1, Tlen);
yystate(52, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 1, Tlen);
yystate(52, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 1, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 1, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 1, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 1, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,52};
yystate(51, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(50, [114|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 27, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(50, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(50, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,50};
yystate(49, [110|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,49};
yystate(48, [105|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,48};
yystate(47, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line+1, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 124 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 126 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [116|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,46};
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 26, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,45};
yystate(44, [108|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,44};
yystate(43, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(42, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,41};
yystate(40, [101|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 27, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(40, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(40, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,40};
yystate(39, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line+1, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 124 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 126 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(37, [105|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 27, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(37, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(37, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,37};
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 13, Tlen);
yystate(36, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 13, Tlen);
yystate(36, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 13, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 13, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 13, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 13, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,36};
yystate(35, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 9, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,34};
yystate(33, [108|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 27, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(33, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(33, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,33};
yystate(32, [97|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,32};
yystate(31, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(30, [107|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 27, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(30, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(30, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 106 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 108, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,30};
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 19, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,29};
yystate(28, [115|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,28};
yystate(27, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [115|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 27, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(26, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(26, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,26};
yystate(25, [110|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [102|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 109 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,25};
yystate(24, [104|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,24};
yystate(23, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line+1, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 43 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [97|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 27, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(22, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(22, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,22};
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 14, Tlen);
yystate(21, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 14, Tlen);
yystate(21, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 14, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 14, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 14, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 14, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,21};
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 0, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,20};
yystate(19, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(18, [116|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 27, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(18, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(18, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,18};
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 6, Tlen);
yystate(17, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 6, Tlen);
yystate(17, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 6, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 6, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 6, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 6, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,17};
yystate(16, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(15, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line+1, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [102|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 27, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(14, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(14, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,14};
yystate(13, [110|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [109|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [108|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(11, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [101|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 27, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(10, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(10, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,10};
yystate(9, [100|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,9};
yystate(8, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(7, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 10, Tlen);
yystate(6, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 10, Tlen);
yystate(6, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 10, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 10, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 10, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 10, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,6};
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 11, Tlen);
yystate(5, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 11, Tlen);
yystate(5, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 11, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 11, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 11, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 11, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,5};
yystate(4, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(3, Ics, Line, Tlen+1, 3, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,3};
yystate(2, [101|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 27, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(2, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(2, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,2};
yystate(1, [115|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [46|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(41, Ics, Line, Tlen+1, 27, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,1};
yystate(0, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, _, _, _) ->
    yyaction_28();
yyaction(29, _, _, _) ->
    yyaction_29();
yyaction(30, _, _, _) ->
    yyaction_30();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/cf_lexer.xrl", 69).
yyaction_0(TokenChars, TokenLine) ->
     { token, { bash, TokenLine, TokenChars } } .

-compile({inline,yyaction_1/2}).
-file("src/cf_lexer.xrl", 70).
yyaction_1(TokenChars, TokenLine) ->
     { token, { python, TokenLine, TokenChars } } .

-compile({inline,yyaction_2/2}).
-file("src/cf_lexer.xrl", 71).
yyaction_2(TokenChars, TokenLine) ->
     { token, { r, TokenLine, TokenChars } } .

-compile({inline,yyaction_3/2}).
-file("src/cf_lexer.xrl", 73).
yyaction_3(TokenChars, TokenLine) ->
     { token, { intlit, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("src/cf_lexer.xrl", 74).
yyaction_4(TokenChars, TokenLine) ->
     { token, { strlit, TokenLine, trim_strlit (TokenChars) } } .

-compile({inline,yyaction_5/2}).
-file("src/cf_lexer.xrl", 75).
yyaction_5(TokenChars, TokenLine) ->
     { token, { body, TokenLine, trim_body (TokenChars) } } .

-compile({inline,yyaction_6/2}).
-file("src/cf_lexer.xrl", 76).
yyaction_6(TokenChars, TokenLine) ->
     { token, { beginif, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("src/cf_lexer.xrl", 77).
yyaction_7(TokenChars, TokenLine) ->
     { token, { colon, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/2}).
-file("src/cf_lexer.xrl", 78).
yyaction_8(TokenChars, TokenLine) ->
     { token, { comma, TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("src/cf_lexer.xrl", 79).
yyaction_9(TokenChars, TokenLine) ->
     { token, { deftask, TokenLine, TokenChars } } .

-compile({inline,yyaction_10/2}).
-file("src/cf_lexer.xrl", 80).
yyaction_10(TokenChars, TokenLine) ->
     { token, { else, TokenLine, TokenChars } } .

-compile({inline,yyaction_11/2}).
-file("src/cf_lexer.xrl", 81).
yyaction_11(TokenChars, TokenLine) ->
     { token, { endif, TokenLine, TokenChars } } .

-compile({inline,yyaction_12/2}).
-file("src/cf_lexer.xrl", 82).
yyaction_12(TokenChars, TokenLine) ->
     { token, { eq, TokenLine, TokenChars } } .

-compile({inline,yyaction_13/2}).
-file("src/cf_lexer.xrl", 83).
yyaction_13(TokenChars, TokenLine) ->
     { token, { file, TokenLine, TokenChars } } .

-compile({inline,yyaction_14/2}).
-file("src/cf_lexer.xrl", 84).
yyaction_14(TokenChars, TokenLine) ->
     { token, { in, TokenLine, TokenChars } } .

-compile({inline,yyaction_15/2}).
-file("src/cf_lexer.xrl", 85).
yyaction_15(TokenChars, TokenLine) ->
     { token, { lbrace, TokenLine, TokenChars } } .

-compile({inline,yyaction_16/2}).
-file("src/cf_lexer.xrl", 86).
yyaction_16(TokenChars, TokenLine) ->
     { token, { lparen, TokenLine, TokenChars } } .

-compile({inline,yyaction_17/2}).
-file("src/cf_lexer.xrl", 87).
yyaction_17(TokenChars, TokenLine) ->
     { token, { lsquarebr, TokenLine, TokenChars } } .

-compile({inline,yyaction_18/2}).
-file("src/cf_lexer.xrl", 88).
yyaction_18(TokenChars, TokenLine) ->
     { token, { ltag, TokenLine, TokenChars } } .

-compile({inline,yyaction_19/2}).
-file("src/cf_lexer.xrl", 89).
yyaction_19(TokenChars, TokenLine) ->
     { token, { nil, TokenLine, TokenChars } } .

-compile({inline,yyaction_20/2}).
-file("src/cf_lexer.xrl", 90).
yyaction_20(TokenChars, TokenLine) ->
     { token, { rbrace, TokenLine, TokenChars } } .

-compile({inline,yyaction_21/2}).
-file("src/cf_lexer.xrl", 91).
yyaction_21(TokenChars, TokenLine) ->
     { token, { rparen, TokenLine, TokenChars } } .

-compile({inline,yyaction_22/2}).
-file("src/cf_lexer.xrl", 92).
yyaction_22(TokenChars, TokenLine) ->
     { token, { rsquarebr, TokenLine, TokenChars } } .

-compile({inline,yyaction_23/2}).
-file("src/cf_lexer.xrl", 93).
yyaction_23(TokenChars, TokenLine) ->
     { token, { rtag, TokenLine, TokenChars } } .

-compile({inline,yyaction_24/2}).
-file("src/cf_lexer.xrl", 94).
yyaction_24(TokenChars, TokenLine) ->
     { token, { semicolon, TokenLine, TokenChars } } .

-compile({inline,yyaction_25/2}).
-file("src/cf_lexer.xrl", 95).
yyaction_25(TokenChars, TokenLine) ->
     { token, { string, TokenLine, TokenChars } } .

-compile({inline,yyaction_26/2}).
-file("src/cf_lexer.xrl", 96).
yyaction_26(TokenChars, TokenLine) ->
     { token, { then, TokenLine, TokenChars } } .

-compile({inline,yyaction_27/2}).
-file("src/cf_lexer.xrl", 98).
yyaction_27(TokenChars, TokenLine) ->
     { token, { id, TokenLine, TokenChars } } .

-compile({inline,yyaction_28/0}).
-file("src/cf_lexer.xrl", 100).
yyaction_28() ->
     skip_token .

-compile({inline,yyaction_29/0}).
-file("src/cf_lexer.xrl", 101).
yyaction_29() ->
     skip_token .

-compile({inline,yyaction_30/0}).
-file("src/cf_lexer.xrl", 102).
yyaction_30() ->
     skip_token .

-file("/usr/local/lib/erlang/lib/parsetools-2.1.1/include/leexinc.hrl", 290).
