---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp: ['26.0', '27.0']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: '3.24.0'
      - run: rebar3 compile
      - run: rebar3 xref
      - run: rebar3 efmt -c
      - run: rebar3 eunit
      - run: rebar3 dialyzer
      - run: rebar3 edoc
